//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionRecordsArchive
    {
        public int ArchiveId { get; set; }
        public Nullable<int> RecordId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BearingTypeId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    }
}
